### ISSUE TITLE
Detailed example ?

### ISSUE THREAD

**Issue by pbacon42** [sarus-tech/tf2-published-models#2]
Hi,

First of all thank you very much for your repo.

I am studying your CNP implementation and, as for the other networks you propose, you stop the script to the training of the model. Could you please provide the code to fully reproduce the figure you show (especially for the regression) ?

Hopefully this detailed example will call the plot functions implemented in the utils/ directory.

Thank you in advance for your assistance.

Cheers,
Philippe

**Comment by Joooohan** [comment]
Hi Philippe,

The figures we show can be visualized with [tensorboard](https://www.tensorflow.org/tensorboard/get_started).

The images generated during training are saved under the `logs` directory of where you started the script from.

What you can do is 
```shell
cd cnp/
python train.py
tensorboard --logdir logs
```

And then go to `localhost:6006` with your favorite web browser. Hope you can see them now !

**Comment by pbacon42** [comment]
Hi Johan,

Thank you for your reply. 

I solved my problem without actually using tensorboard. I was looking for a pure python code.
